#!/bin/sh
set -e

# Copyright (c) 2012 Jake Petroules. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

USAGE="Usage: `basename $0` [-hfn] files\n
\n
\t-h\tDisplay this help\n
\t-f\tDisplay filenames before each download URL\n
\t-n\tOutput no newlines\n"
PREFIX=''
SUFFIX='\n'

# Parse options
while getopts hfn OPT; do
    case "$OPT" in
        h)
            echo $USAGE
            exit 0
            ;;
        f)
            PREFIX='$file'
            ;;
        n)
            SUFFIX=''
            ;;
        \?)
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

# Remove options parsed
shift `expr $OPTIND - 1`

# Need at least one filename
if [ $# -eq 0 ] ; then
    echo $USAGE >&2
    exit 1
fi

# Display output
for file in "$@"
do
    if [ ! -z "$PREFIX" ] ; then
        echo "$file: \c"
    fi

	xattr -p -x com.apple.metadata:kMDItemWhereFroms "$file" | xxd -r -p | \
	plutil -convert xml1 -o - - | xmllint --xpath "/plist/array/string/text()" -
	echo "$SUFFIX\c"
done
